name: reliance_industries_limited_ril
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  #a #b
  app_settings: ^5.0.0
  bottom_bar_matu: ^1.3.0

  #c
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.2.3
  
  #d
  dio: ^5.3.0
  android_id: ^0.3.3
  device_info_plus: ^9.0.2
  dart_ipify: ^1.1.1

  #g
  go_router: ^8.2.0
  google_fonts: ^5.1.0
  geolocator: ^9.0.2
 

  #q
  qr_code_scanner: ^1.0.1

  #l
  location: ^5.0.1
  latlong2: ^0.9.0
  
  #m
  material_design_icons_flutter: ^7.0.7296
  mobile_number: ^2.1.1

  #f
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2
  flutter_native_splash: ^2.3.1
  

  #p
  permission_handler: ^10.4.3
  package_info_plus: ^4.0.2

  #s
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    icon_background_color: "#ffffff"



flutter:
  uses-material-design: true

  assets:
    - assets/images/
